### ISSUE TITLE
GUI showing $postalCode instead of price

### ISSUE THREAD

**Issue by w-yuchen** [AY2021S2-CS2103T-T13-4/tp#119]
![image](https://user-images.githubusercontent.com/32015928/111528304-f2e97980-879b-11eb-8db1-436f076972a9.png)
As seen in the image, the price field is displaying `postalCode`.

**Comment by candyhy** [comment]
hey, I've fixed the bug that doesn't display postal code. However, about price, have to consult junwei on this because he is adding the price of the property as client info actually, not as part of property attribute itself

**Comment by w2vgd** [comment]
I think that we originally discussed and decided that the asking price should be an optional "client asking price", so I had put it under client info. We can discuss more about this in the next meeting to see if we want to change it to be under property directly.
