### ISSUE TITLE
As a careless user, I want to be able to categorize housing type based on predefined tags to prevent typos while keying in information

### ISSUE THREAD

**Issue by w2vgd** [AY2021S2-CS2103T-T13-4/tp#12]
so that I do not accidentally store the wrong information.

**Comment by w-yuchen** [comment]
15 March discussion: 

- Limited set of tags
- Housing types
- Currently not under tag but under property type
- Reuse the code from addressbook
- Add extra tags: bedroom and bathroom numbers, both existing as compulsary tags

**Comment by w2vgd** [comment]
Only property types "hdb", "condo" and "landed" and all forms of their capitalization are allowed for the `PropertyType` attribute of a property
